@startuml KlassediagramMapper

package "Interface" {
    interface StopService {
        + String calculateTransportAtStop(Stop, String)
        + Stop findStopByName(List<Stop>, String)
        + String findNextDepartureTime(Stop, String)
        + int calculateTravelTime(Stop, String, Stop)
    }
    interface RouteService {
        + Route calculateRoute(ArrayList<Route>, String, String)
    }
}

package "Service" {
    class StopLogic {}
    class RouteLogic {}
    class "RouteLogic.Result" as Result {
        - boolean success
        - String transportType
        - String routeName
        - String message
        - String departureFromTerminal
        - String startLocation
        - String endLocation
        - String arrivalAtStartStop
        - String arrivalAtEndStop
        - int travelTime
    }

    RouteLogic +-- Result : Inner Class

}

package "TravelEnteties" {
    class Stop {
        - String stopId
        - String location
        - String name
        - String departureTime
        - ArrayList<String> departureTimes
        - int minutesAfterDeparture
    }
    class Route {
        - String routeId
        - String routeName
        - Transport transport
        - double price
        - ArrayList<Stop> stops
    }
    class Transport {
        - String transportId
        - String routeId
        - String routeName
        - String transportType
        - String startLocation
        - String endLocation
        - String departureTime
        - String arrivalTime
        + double estimateTravelTime()
    }

    package InternalDTO {
        class RouteDTO {
            Result {
                - boolean success
                - String transportType
                - String routeName
                - String message
                - String departureFromTerminal
                - String startLocation
                - String endLocation
                - String arrivalAtStartStop
                - String arrivalAtEndStop
                - int travelTime
            }
        class ResultDTO {
            - String startLocation
            - String endLocation
            - String transportType
            - double price
            - int travelTime
            - ArrayList<RouteDTO> routes
        }
    }
}

package "Controller" {
    class RouteController {
        Get
        Post
        Put
        Delete 
    }

    class ResultController {
        Get
        Post
        Put
        Delete
    }

}
    note top of Controller
        Controller will be integrated with Frontend later
    end note

package "Data" {
    class RouteReader
}

package "APIHandler" {
    class APIRouteDTO
}

Interface.StopService <|.. Service.StopLogic : implements
Interface.RouteService <|.. Service.RouteLogic : implements

Service.RouteLogic ..> TravelEnteties.Stop : uses
Service.RouteLogic ..> TravelEnteties.Route : uses
Service.StopLogic ..> TravelEnteties.Stop : uses

APIHandler.APIRouteDTO ..> Data.RouteReader : deserializes DTO-data 
Data.RouteReader ..> TravelEnteties.Route : creates/maps Route

TravelEnteties.Route *-- TravelEnteties.Transport : contains
TravelEnteties.Route o-- TravelEnteties.Stop : uses

Controller.RouteController ..> TravelEnteties.InternalDTO.RouteDTO : serializes

Controller.ResultController ..> TravelEnteties.InternalDTO.ResultDTO : serializes

@enduml