@startuml KlassediagramMapper

package "Interface" {
    interface StopService {
        + String calculateTransportAtStop(Stop, String)
        + Stop findStopByName(List<Stop>, String)
        + String findNextDepartureTime(Stop, String)
        + int calculateTravelTime(Stop, String, Stop)
    }
    interface RouteService {
        + Route calculateRoute(ArrayList<Route>, String, String)
    }
}

package "Service" {
    class StopLogic 
    class RouteLogic 
}

package "TravelEnteties" {
    class Stop {
        - String stopId
        - String location
        - String name
        - String departureTime
        - ArrayList<String> departureTimes
        - int minutesAfterDeparture
    }
    class Route {
        - String routeId
        - String routeName
        - Transport transport
        - double price
        - ArrayList<Stop> stops
    }
    class Transport {
        - String transportId
        - String routeId
        - String routeName
        - String transportType
        - String startLocation
        - String endLocation
        - String departureTime
        - String arrivalTime
        + double estimateTravelTime()
    }
}


package "Data" {
        class RouteReader
        class RouteWriter
}



' Relasjoner
Interface.StopService <|.. Service.StopLogic : implements
Interface.RouteService <|.. Service.RouteLogic : implements

Service ..> TravelEnteties.Stop : uses
Service.RouteLogic ..> TravelEnteties.Route

Data.RouteReader ..> TravelEnteties.Route : "reads route data (with stops and transport)"

TravelEnteties.Route *-- TravelEnteties.Transport : contains
TravelEnteties.Route o-- TravelEnteties.Stop : uses

@enduml
